app:
    domain: localhost
    kind: development
    port: 5000
    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFjY291bnQtbWFuYWdlbWVudC1zZXJ2aWNlIiwiaWF0IjoxNjAzOTA3NzY5LCJhdWQiOiJhY2NvdW50LW1hbmFnZW1lbnQtc2VydmljZSIsImlzcyI6ImFjY291bnQtbWFuYWdlbWVudC1zZXJ2aWNlIiwic3ViIjoiYWNjb3VudC1tYW5hZ2VtZW50LXNlcnZpY2UifQ.-DTe2a_5_ESzW8Cqh-SIqPP2wws8z-8DflgbbKKAgy4

cookie:
    secret: cookiesigningbylogpost
    options:
        doamain: localhost
        httpOnly: false
        secure: false
        maxAge: 1000000
        signed: true

jwt:
    email_token:
        secret:
            jwt_secret: logpostemailconfirm
        options:
            expires_in: 10m
            issuer: logpost
            audience: mailer
    refresh_token:
        secret:
            jwt_secret: logpostrefreshtoken
        options:
            expires_in: 10m
            issuer: logpost
            audience: logpost
    access_token:
        secret:
            jwt_secret: logpostprivateroute
        options:
            expires_in: 1m
            issuer: logpost
            audience: logpost

shipper:
    api:
        base_url: http://localhost:8080
        prefix_route: /shipper

carrier:
    api:
        base_url: http://localhost:8081
        prefix_route: /carrier

frontend:
    domain: localhost
    port: 3000

nodemailer:
    auth:
        gmail:
            username: logpost.bot@gmail.com
            password: logpost2020

redis:
    port: 18491
    host: redis-18491.c228.us-central1-1.gce.cloud.redislabs.com
    password: 3mKpjRKIKljcHG1EXRpHe9Sjivxp5UoR
