app:
    domain: localhost
    kind: production
    port: 5000
    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFjY291bnQtbWFuYWdlbWVudC1zZXJ2aWNlIiwiaXNDb25maXJtRW1haWwiOnRydWUsInJvbGUiOiJzcnYiLCJpYXQiOjE2MDk2NzAxOTUsImF1ZCI6ImFjY291bnQtbWFuYWdlbWVudC1zZXJ2aWNlIiwiaXNzIjoiYWNjb3VudC1tYW5hZ2VtZW50LXNlcnZpY2UiLCJzdWIiOiJhY2NvdW50LW1hbmFnZW1lbnQtc2VydmljZSJ9.2XXUaOp_V28yHmtRZ0HLOiZVtViFW0Mcp42LIeTrwuw

cors:
    origin: ["http://127.0.0.1:3000", "https://logpost.netlify.app"]
    credentials: true
    exposedHeaders: ["set-cookie"]

cookie:
    secret: cookiesigningbylogpost
    options:
        doamain: localhost
        httpOnly: true
        secure: true
        expires: 14
        signed: true

jwt:
    email_token:
        secret:
            jwt_secret: logpostemailconfirm
        options:
            expires_in: 10m
            issuer: logpost
            audience: mailer
    refresh_token:
        secret:
            jwt_secret: logpostrefreshtoken
        options:
            expires_in: 14d
            issuer: logpost
            audience: logpost
    access_token:
        secret:
            jwt_secret: logpostprivateroute
        options:
            expires_in: 10m
            issuer: logpost
            audience: logpost

shipper:
    api:
        base_url: https://shipper-management-service-logpost-stag-qjrfn6j7kq-as.a.run.app
        prefix_route: /shipper

carrier:
    api:
        base_url: https://carrier-management-service-logpost-stag-qjrfn6j7kq-as.a.run.app
        prefix_route: /carrier

frontend:
    base_url: http://localhost:3000
    domain: localhost
    port: 3000

nodemailer:
    auth:
        gmail:
            username: logpost.bot@gmail.com
            password: logpost2020

redis:
    port: 18491
    host: redis-18491.c228.us-central1-1.gce.cloud.redislabs.com
    password: 3mKpjRKIKljcHG1EXRpHe9Sjivxp5UoR
